

DROP TABLE IF EXISTS order_information;
  
CREATE TABLE order_information (
  USER_TOKEN VARCHAR NOT NULL,
  PURCHASE_TIME TIMESTAMP NOT NULL,
  TRANSACTION_TOKEN VARCHAR NOT NULL,
  SERVICE_TOKEN VARCHAR NOT NULL
  
);
DROP TABLE IF EXISTS order_data;

CREATE TABLE order_data (
  ORDER_DATA_ID INT NOT NULL,
  PRODUCT_NAME VARCHAR NOT NULL,
  QUANTITY INT NOT NULL,
  BRAND_NAME VARCHAR NOT NULL,
  MODEL_NUMBER VARCHAR NOT NULL
 );
 
 CREATE TABLE groceries_inventory (
  ID INT NOT NULL,
  ORDER_STATUS VARCHAR NOT NULL,
  BRAND_NAME  VARCHAR NOT NULL,
  MODEL_NUMBER VARCHAR NOT NULL,
  PRODUCT_NAME VARCHAR NOT NULL,
  QUANTITY INT NOT NULL
 );
 
 